namespace:
  name: prod 

service:
  port: 7111
  type: ClusterIP

replicaCount: 5

image:
  repository: tomiwasalau01/techtrends 
  tag: V2.0.0
  pullPolicy: Always

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    memory: 256Mi
    cpu: 500m